extern alias JetBrainsRoot;
global using MeansImplicitUse = JetBrainsRoot::JetBrains.Annotations.MeansImplicitUseAttribute;
global using Next.Api;
global using Next.Api.Logs;
global using Next.Api.Utils;
global using Next.Api.Enums;
global using Next.Api.Config;
global using static Next.Api.Utils.StreamUtils;
global using static Next.Api.APIHarmony;
global using static Next.Api.Logs.FastLog;